"""edit edited_at column in models

Revision ID: 2759403d2b4a
Revises: bb6e711ff3c5
Create Date: 2024-08-05 08:49:13.792155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2759403d2b4a'
down_revision: Union[str, None] = 'bb6e711ff3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
