"""delete Product table and init ProductsList table

Revision ID: fc998da1d87b
Revises: dcd7feecb4c3
Create Date: 2024-08-01 11:59:46.742306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc998da1d87b'
down_revision: Union[str, None] = 'dcd7feecb4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('ean', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_list_count'), 'products_list', ['count'], unique=False)
    op.create_index(op.f('ix_products_list_ean'), 'products_list', ['ean'], unique=False)
    op.create_index(op.f('ix_products_list_id'), 'products_list', ['id'], unique=False)
    op.create_index(op.f('ix_products_list_title'), 'products_list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_list_title'), table_name='products_list')
    op.drop_index(op.f('ix_products_list_id'), table_name='products_list')
    op.drop_index(op.f('ix_products_list_ean'), table_name='products_list')
    op.drop_index(op.f('ix_products_list_count'), table_name='products_list')
    op.drop_table('products_list')
    # ### end Alembic commands ###
